apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: fsgq
  name: rolling-nginx
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      type: fsgq
  template:
    metadata:
      labels:
        type: fsgq
    spec:
      containers:
      - name: nginx
        image: nginx:1.9
