apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dtwnvoih-cluster-role-binding
  namespace: default
roleRef:
  name: dtwnvoih-cluster-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: dtwnvoih
    namespace: default
